"""schema inicial - 10 tabelas

Revision ID: 198a6f2c9c79
Revises: 
Create Date: 2026-05-14 22:05:15.142207

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '198a6f2c9c79'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('acao', sa.String(length=120), nullable=False),
    sa.Column('recurso', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_timestamp'), 'auditoria', ['timestamp'], unique=False)
    op.create_table('centros_custo',
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('bloco_predio', sa.String(length=120), nullable=True),
    sa.Column('centro_custo_pai_id', sa.UUID(), nullable=True),
    sa.Column('total_colaboradores', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['centro_custo_pai_id'], ['centros_custo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_centros_custo_centro_custo_pai_id'), 'centros_custo', ['centro_custo_pai_id'], unique=False)
    op.create_table('dominios',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('polaridade', sa.SmallInteger(), nullable=False),
    sa.Column('ordem_apresentacao', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('polaridade IN (-1, 1)', name='ck_dominios_polaridade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao_admin',
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_origem', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expirada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessao_admin_usuario'), 'sessao_admin', ['usuario'], unique=False)
    op.create_table('colaborador_import',
    sa.Column('matricula', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=False),
    sa.Column('status_distribuicao', postgresql.ENUM('pendente', 'distribuida', 'confirmada', name='status_distribuicao'), server_default='pendente', nullable=False),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_index(op.f('ix_colaborador_import_centro_custo_id'), 'colaborador_import', ['centro_custo_id'], unique=False)
    op.create_table('credencial',
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=False),
    sa.Column('consumida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_sessao_temporario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('senha_hash'),
    sa.UniqueConstraint('token_sessao_temporario')
    )
    op.create_index(op.f('ix_credencial_centro_custo_id'), 'credencial', ['centro_custo_id'], unique=False)
    op.create_table('itens',
    sa.Column('dominio_id', sa.UUID(), nullable=False),
    sa.Column('texto_pergunta', sa.Text(), nullable=False),
    sa.Column('ordem_apresentacao', sa.Integer(), nullable=False),
    sa.Column('escala_tipo', sa.String(length=1), nullable=False),
    sa.Column('invertido', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("escala_tipo IN ('A', 'B')", name='ck_itens_escala_tipo'),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_dominio_id'), 'itens', ['dominio_id'], unique=False)
    op.create_table('questionarios',
    sa.Column('token_anonimo', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('iniciado', 'concluido', 'abandonado', name='questionario_status'), server_default='iniciado', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_anonimo')
    )
    op.create_index(op.f('ix_questionarios_centro_custo_id'), 'questionarios', ['centro_custo_id'], unique=False)
    op.create_table('lembretes',
    sa.Column('matricula', sa.String(length=60), nullable=False),
    sa.Column('tipo', postgresql.ENUM('email', 'sms', name='lembrete_tipo'), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('pendente', 'enviado', 'falhou', name='lembrete_status'), server_default='pendente', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula'], ['colaborador_import.matricula'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lembretes_matricula'), 'lembretes', ['matricula'], unique=False)
    op.create_table('respostas',
    sa.Column('questionario_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.SmallInteger(), nullable=False),
    sa.Column('submetida_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('valor BETWEEN 0 AND 4', name='ck_respostas_valor'),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_item_id'), 'respostas', ['item_id'], unique=False)
    op.create_index(op.f('ix_respostas_questionario_id'), 'respostas', ['questionario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_questionario_id'), table_name='respostas')
    op.drop_index(op.f('ix_respostas_item_id'), table_name='respostas')
    op.drop_table('respostas')
    op.drop_index(op.f('ix_lembretes_matricula'), table_name='lembretes')
    op.drop_table('lembretes')
    op.drop_index(op.f('ix_questionarios_centro_custo_id'), table_name='questionarios')
    op.drop_table('questionarios')
    op.drop_index(op.f('ix_itens_dominio_id'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('ix_credencial_centro_custo_id'), table_name='credencial')
    op.drop_table('credencial')
    op.drop_index(op.f('ix_colaborador_import_centro_custo_id'), table_name='colaborador_import')
    op.drop_table('colaborador_import')
    op.drop_index(op.f('ix_sessao_admin_usuario'), table_name='sessao_admin')
    op.drop_table('sessao_admin')
    op.drop_table('dominios')
    op.drop_index(op.f('ix_centros_custo_centro_custo_pai_id'), table_name='centros_custo')
    op.drop_table('centros_custo')
    op.drop_index(op.f('ix_auditoria_timestamp'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###

    # ENUMs criados implicitamente pelo create_table no upgrade não são
    # removidos pelo drop_table — dropados explicitamente para o downgrade
    # ser idempotente e não quebrar um upgrade posterior.
    op.execute("DROP TYPE IF EXISTS questionario_status")
    op.execute("DROP TYPE IF EXISTS status_distribuicao")
    op.execute("DROP TYPE IF EXISTS lembrete_tipo")
    op.execute("DROP TYPE IF EXISTS lembrete_status")
