"""colaborador_import: nome_enc + email_enc

Revision ID: 483637f27bc4
Revises: 198a6f2c9c79
Create Date: 2026-05-15 19:55:27.461529

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483637f27bc4'
down_revision: str | Sequence[str] | None = '198a6f2c9c79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colaborador_import', sa.Column('nome_enc', sa.LargeBinary(), nullable=True))
    op.add_column('colaborador_import', sa.Column('email_enc', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colaborador_import', 'email_enc')
    op.drop_column('colaborador_import', 'nome_enc')
    # ### end Alembic commands ###
