"""auth: operadores + refactor sessao_admin

Revision ID: f68810e21415
Revises: 483637f27bc4
Create Date: 2026-05-15 20:02:27.540680

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f68810e21415'
down_revision: str | Sequence[str] | None = '483637f27bc4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # cria o enum antes de qualquer ALTER TABLE que o referencie
    sa.Enum(
        'pendente_totp', 'ativa', 'revogada',
        name='sessao_admin_estado',
    ).create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operadores',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('nome_enc', sa.LargeBinary(), nullable=True),
    sa.Column('sobrenome_enc', sa.LargeBinary(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('sessao_admin', sa.Column('operador_id', sa.UUID(), nullable=False))
    op.add_column('sessao_admin', sa.Column('token_hash', sa.LargeBinary(), nullable=False))
    op.add_column('sessao_admin', sa.Column('estado', postgresql.ENUM('pendente_totp', 'ativa', 'revogada', name='sessao_admin_estado', create_type=False), server_default='ativa', nullable=False))
    op.add_column('sessao_admin', sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sessao_admin', sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessao_admin', sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_sessao_admin_usuario'), table_name='sessao_admin')
    op.create_index(op.f('ix_sessao_admin_operador_id'), 'sessao_admin', ['operador_id'], unique=False)
    op.create_unique_constraint(None, 'sessao_admin', ['token_hash'])
    op.create_foreign_key(None, 'sessao_admin', 'operadores', ['operador_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sessao_admin', 'usuario')
    op.drop_column('sessao_admin', 'expirada_em')
    op.drop_column('sessao_admin', 'iniciada_em')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessao_admin', sa.Column('iniciada_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sessao_admin', sa.Column('expirada_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessao_admin', sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessao_admin', type_='foreignkey')
    op.drop_constraint(None, 'sessao_admin', type_='unique')
    op.drop_index(op.f('ix_sessao_admin_operador_id'), table_name='sessao_admin')
    op.create_index(op.f('ix_sessao_admin_usuario'), 'sessao_admin', ['usuario'], unique=False)
    op.drop_column('sessao_admin', 'revogada_em')
    op.drop_column('sessao_admin', 'expira_em')
    op.drop_column('sessao_admin', 'criada_em')
    op.drop_column('sessao_admin', 'estado')
    op.drop_column('sessao_admin', 'token_hash')
    op.drop_column('sessao_admin', 'operador_id')
    op.drop_table('operadores')
    # cleanup do enum criado neste upgrade
    sa.Enum(name='sessao_admin_estado').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
